"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const HtmlTag_1 = require("./HtmlTag");
const BasicHtml_1 = require("./BasicHtml");
const Server_1 = require("./Server");
var tag = new HtmlTag_1.HtmlTag('');
console.log(BasicHtml_1.htmltemplate);
tag.setTagName('div');
console.log(tag.getTagName());
(0, Server_1.runServer)();
